apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker-service.fullname" . }}
  labels:
    {{- include "worker-service.labels" . | nindent 4 }}
data:
  worker.conf: |
    # Worker configuration
    interval: {{ .Values.worker.interval }}
    cleanup_days: {{ .Values.worker.cleanupDays }}
