apiVersion: v2
name: api-service
description: A Helm chart for API Service microservice
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - api
  - microservice
  - cloud-native
maintainers:
  - name: Sanal Thesis
    email: sanal@example.com
